apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: simrs-dev

commonLabels:
  environment: dev

images:
- name: simrs-backend
  newName: simrs-backend
  newTag: dev
